global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.7.5:8084']
        labels:
          application: 'Product Service Application'
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.7.5:8081']
        labels:
          application: 'Order Service Application'
  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.7.5:8082']
        labels:
          application: 'Inventory Service Application'
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.7.5:8085']
        labels:
          application: 'Notification Service Application'
  - job_name: 'message-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.7.5:8086']
        labels:
          application: 'Message Service Application'